=== akshatkatre/aws/pipelines/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CustomerList" type="CustomerListType" minOccurs="0" maxOccurs="1"/>
				<xs:element name="GuideList" type="GuideListType" minOccurs="0" maxOccurs="1"/>
				<xs:element name="DestinationList" type="DestinationListType" minOccurs="0" maxOccurs="1"/>
				<xs:element name="TourList" type="TourListType" minOccurs="0" maxOccurs="1"/>	
				<xs:element name="TripList" type="TripListType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:keyref name="StartDestinationIdReference" refer="DestinationId">
			<xs:selector xpath="TourList/Tour/TourItinerary/Day"/>
			<xs:field xpath="@StartDestinationId"/>
		</xs:keyref> 
		<xs:keyref name="EndDestinationIdReference" refer="DestinationId">
			<xs:selector xpath="TourList/Tour/TourItinerary/Day"/>
			<xs:field xpath="@EndDestinationId"/>
		</xs:keyref> 
		<xs:key name="DestinationId">
			<xs:selector xpath="DestinationList/Destination"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:keyref name="CertifiedTourGuideIdReference" refer="GuideId">
			<xs:selector xpath="TourList/Tour/CertifiedGuides/Guide"/>
			<xs:field xpath="@GuideId"/>
		</xs:keyref> 	
		<xs:key name="GuideId">
			<xs:selector xpath="GuideList/Guide"/>
			<xs:field xpath="@Id"/>
		</xs:key>		
		<xs:keyref name="TripCustomerReference" refer="CustomerId">
			<xs:selector xpath="TripList/Trip/Participants/Customer"/>
			<xs:field xpath="@CustomerId"/>
		</xs:keyref> 			
		<xs:key name="CustomerId">
			<xs:selector xpath="CustomerList/Customer"/>
			<xs:field xpath="@Id"/>
		</xs:key>	
		<xs:keyref name="TripTourReference" refer="TourId">
			<xs:selector xpath="TripList/Trip"/>
			<xs:field xpath="@TourId"/>
		</xs:keyref> 	
		<xs:keyref name="TripGuideReference" refer="GuideId">
			<xs:selector xpath="TripList/Trip/TripGuides/TripGuide"/>
			<xs:field xpath="@GuideId"/>
		</xs:keyref> 		
		<xs:key name="TourId">
			<xs:selector xpath="TourList/Tour"/>
			<xs:field xpath="@Id"/>
		</xs:key>			
	</xs:element>
	<xs:complexType name="CustomerListType">
		<xs:sequence>
			<xs:element name="Customer" type="CustomerType" minOccurs="0" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CustomerType">
		<xs:sequence>
			<xs:element ref="PrimaryInformation"/>
			<xs:element ref="Contact"/>
			<xs:element ref="Address"/>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:integer"/>
	</xs:complexType>
	<!--guides-->
	<xs:complexType name="GuideListType">
		<xs:sequence>
			<xs:element name="Guide" type="GuideType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GuideType">
		<xs:sequence>
			<xs:element name="Skills" type="SkillsType"/>
			<xs:element ref="PrimaryInformation"/>
			<xs:element ref="Contact"/>
			<xs:element ref="Address"/>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:integer"/>
	</xs:complexType>
	<xs:complexType name="SkillsType">
		<xs:sequence>
			<xs:element name="Skill"  minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute type="xs:string" name="Details"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>		
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--guides end-->	
	<!--destination start-->
	<xs:complexType name="DestinationListType">
		<xs:sequence>
			<xs:element name="Destination" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="Contact"/>
						<xs:element ref="Address"/>
					</xs:sequence>

					<xs:attribute name="Id" type="xs:integer"/>
					<xs:attribute name="DestinationName" type="xs:string"/>
					<xs:attribute name="DestinationType" type="xs:string"/>
					<xs:attribute name="Access" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--destination end-->
	<!--Tour start-->
	<xs:complexType name="TourListType">
		<xs:sequence>
			<xs:element name="Tour" type="TourType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TourType">
		<xs:sequence>
			<xs:element name="TourFacts" type="TourFactsType" />
			<xs:element name="TourDescription" type="TourDescriptionType" />
			<xs:element name="TourItinerary" type="TourItineraryType" />
			<xs:element name="AdditionalInformationList" type="AdditionalInformationListType" />
			<xs:element name="CertifiedGuides" type="CertifiedGuidesType"/>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:integer"/>
		<xs:attribute name="Name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TourFactsType">
		<xs:attribute name="NoOfDays" type="xs:integer"/>
		<xs:attribute name="NoOfNights" type="xs:integer"/>
		<xs:attribute name="Difficulty" type="xs:string"/>
		<xs:attribute name="IsDogFriendly" type="xs:boolean"/>
		<xs:attribute name="IsAllYear" type="xs:boolean"/>
		<xs:attribute name="Minimum" type="xs:integer"/>
		<xs:attribute name="Maximum" type="xs:integer"/>
		<xs:attribute name="CostPerPerson" type="xs:float"/>
		<xs:attribute name="StartDestination" type="xs:integer"/>
		<xs:attribute name="EndDestination" type="xs:integer"/>
	</xs:complexType>
	<xs:complexType name="TourDescriptionType">
		<xs:attribute name="ShortDescription" type="xs:string"/>
		<xs:attribute name="ExtendedDiscription" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TourItineraryType">
		<xs:sequence>
			<xs:element name="Day" type="DayType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DayType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Category" type="xs:string"/>
				<xs:attribute name="SequenceNo" type="xs:integer"/>
				<xs:attribute name="StartDestinationId" type="xs:integer"/>
				<xs:attribute name="EndDestinationId" type="xs:integer"/>
				<xs:attribute name="NoOfMiles" type="xs:float"/>
				<xs:attribute name="Activities" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>	
	</xs:complexType>
	<xs:complexType name="AdditionalInformationListType">
		<xs:sequence>
			<xs:element name="AdditionalInformation" type="AdditionalInformationType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdditionalInformationType">
		<xs:attribute name="Category">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="INCLUSIONS" />
					<xs:enumeration value="EXTRA_NIGHTS" />
					<xs:enumeration value="TRAVEL_INFO" />
					<xs:enumeration value="WEATHER" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Details" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="CertifiedGuidesType">
		<xs:sequence>
			<xs:element name="Guide" type="TourGuideType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TourGuideType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="GuideId" type="xs:integer"/>
			</xs:extension>
		</xs:simpleContent>	
	</xs:complexType>		
	<!--Tour end-->	
	<xs:complexType name="TripListType">
		<xs:sequence>
			<xs:element name="Trip" type="TripType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	<xs:complexType name="TripType">
		<xs:sequence>
			<xs:element name="TripGuides" type="TripGuidesType" />
			<xs:element name="Participants" type="ParticipantsType" />
		</xs:sequence>
		<xs:attribute name="Id" type="xs:integer"/>
		<xs:attribute name="TourId" type="xs:integer"/>
		<xs:attribute name="StartDate" type="xs:date"/>
		<xs:attribute name="EndDate" type="xs:date"/>
	</xs:complexType>	
	<xs:complexType name="TripGuidesType">
		<xs:sequence>
			<xs:element name="TripGuide" type="TripGuideType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	<xs:complexType name="TripGuideType">
		<xs:attribute name="GuideId" type="xs:integer"/>
	</xs:complexType>		
	<xs:complexType name="ParticipantsType">
		<xs:sequence>
			<xs:element name="Customer" type="TripCustomerType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>		
	<xs:complexType name="TripCustomerType">
		<xs:attribute name="CustomerId" type="xs:integer"/>
		<xs:attribute name="SatisfactionScore" type="xs:integer"/>
	</xs:complexType>	

	<!--Trip end-->
	<xs:element name="PrimaryInformation">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="Title"/>
					<xs:attribute type="xs:string" name="FirstName" use="required"/>
					<xs:attribute type="xs:string" name="LastName" use="required"/>
					<xs:attribute type="xs:date" name="DateOfBirth" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Contact">
		<xs:complexType >
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="EmailId" use="required"/>
					<xs:attribute type="xs:string" name="MobilePhone" use="required"/>
					<xs:attribute type="xs:string" name="Landline" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Address">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="AddressLine1" use="required"/>
					<xs:attribute type="xs:string" name="AddressLine2" />
					<xs:attribute type="xs:string" name="AddressLine3" />
					<xs:attribute type="xs:string" name="AddressLine4" />
					<xs:attribute type="xs:string" name="Region" />
					<xs:attribute type="xs:string" name="PostCode" use="required"/>
					<xs:attribute type="xs:string" name="Country" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>
<!--
https://www.w3schools.com/xml/el_element.asp
https://stackoverflow.com/questions/9876959/how-to-declare-an-attribute-id-in-xml
https://stackoverflow.com/questions/31210735/how-to-add-multiple-attribute-in-single-element-using-xsd
https://stackoverflow.com/questions/38711466/xsdcomplextype-with-children-attributes-and-restrictions
-->

=== akshatkatre/aws/pipelines/data.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<CustomerList>
		<Customer Id="100">
			<PrimaryInformation Title="Mr" FirstName="Johnathan" LastName="Smith" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Johnathan.Smith@somedomain.com" MobilePhone="566093" Landline="9939393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="101">
			<PrimaryInformation Title="Mrs" FirstName="Milly" LastName="Cook" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Milly.Cook@somedomain.com" MobilePhone="0789918899" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="102">
			<PrimaryInformation Title="Mrs" FirstName="Joel " LastName="Reed" DateOfBirth="1978-12-01"/>
			<Contact EmailId="Joel.Reed@somedomain.com" MobilePhone="08393931" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="wl2" Country="GB"/>
		</Customer>		
		<Customer Id="104">
			<PrimaryInformation Title="Mr" FirstName="Eric" LastName="Shuman" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Eric.Shuman@somedomain.com" MobilePhone="2032002" Landline="9939393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="105">
			<PrimaryInformation Title="Mrs" FirstName="Jenny" LastName="Smith" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Jenny.Smith@somedomain.com" MobilePhone="677748830" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="106">
			<PrimaryInformation Title="Mr" FirstName="Rowan" LastName="Boyle" DateOfBirth="1978-12-01"/>
			<Contact EmailId="Rowan.Boyle@somedomain.com" MobilePhone="3993827" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="wl2" Country="GB"/>
		</Customer>	
		<Customer Id="107">
			<PrimaryInformation Title="Miss" FirstName="Stacey" LastName="Durham" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Stacey.Durham@somedomain.com" MobilePhone="90002000" Landline="9939393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="108">
			<PrimaryInformation Title="Mr" FirstName="Cleo" LastName="Carson" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Cleo.Carson@somedomain.com" MobilePhone="205666785" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="109">
			<PrimaryInformation Title="Miss" FirstName="Holly" LastName="Wilson" DateOfBirth="1978-12-01"/>
			<Contact EmailId="Holly.Wilson@somedomain.com" MobilePhone="9663325479" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="wl2" Country="GB"/>
		</Customer>		
		<Customer Id="110">
			<PrimaryInformation Title="Miss" FirstName="Daniella" LastName="Padilla" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Daniella.Padilla@somedomain.com" MobilePhone="839399693" Landline="9939393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="111">
			<PrimaryInformation Title="Mr" FirstName="Felix" LastName="Mendez" DateOfBirth="1968-12-01"/>
			<Contact EmailId="Felix.Mendez@somedomain.com" MobilePhone="66666931" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="SL1" Country="GB"/>
		</Customer>
		<Customer Id="112">
			<PrimaryInformation Title="Mrs" FirstName="Evangeline" LastName="Blake" DateOfBirth="1978-12-01"/>
			<Contact EmailId="Evangeline.Blake@somedomain.com" MobilePhone="559983931" Landline="99319393"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="wl2" Country="GB"/>
		</Customer>			
	</CustomerList>
	<GuideList>
		<Guide Id="1200">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Miss" FirstName="Kelly" LastName="Armstorng" DateOfBirth="1990-12-01"/>
			<Contact EmailId="Kelly.Armstorng@somedomain.com" MobilePhone="180093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>
		<Guide Id="1201">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Mr" FirstName="Marshal" LastName="Ulrich" DateOfBirth="1960-12-01"/>
			<Contact EmailId="Marshal.Ulrich@somedomain.com" MobilePhone="2380093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>
		<Guide Id="1202">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Mr" FirstName="Jason" LastName="Bourne" DateOfBirth="1970-12-01"/>
			<Contact EmailId="Jason.Bourne@somedomain.com" MobilePhone="89880093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>	
		<Guide Id="1204">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Miss" FirstName="Jenny" LastName="Armstorng" DateOfBirth="1990-12-01"/>
			<Contact EmailId="Jenny.armstrong@company.com" MobilePhone="776380093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>
		<Guide Id="1205">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Mr" FirstName="Richard" LastName="Feynman" DateOfBirth="1960-12-01"/>
			<Contact EmailId="Richard.Feynman@somedomain.com" MobilePhone="567980093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>
		<Guide Id="1206">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Mr" FirstName="Lucius" LastName="Feltman" DateOfBirth="1970-12-01"/>
			<Contact EmailId="Lucius.Feltman@somedomain.com" MobilePhone="327880093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>	
		<Guide Id="1207">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Miss" FirstName="Missy" LastName="Carlton" DateOfBirth="1990-12-01"/>
			<Contact EmailId="Missy.Carlton@somedomain.com" MobilePhone="987680093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>
		<Guide Id="1208">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Mr" FirstName="James" LastName="Bose" DateOfBirth="1960-12-01"/>
			<Contact EmailId="James.Bose@somedomain.com" MobilePhone="3325480093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>
		<Guide Id="1209">
			<Skills>
				<Skill Details="First Aid"/>
				<Skill Details="Mountain Class 1"/>
			</Skills>
			<PrimaryInformation Title="Mr" FirstName="Rick" LastName="Coffee" DateOfBirth="1970-12-01"/>
			<Contact EmailId="Rick.Coffee@somedomain.com" MobilePhone="9963280093" Landline="9933"/>
			<Address AddressLine1="Line 1" AddressLine2="" AddressLine3="" AddressLine4="" Region="" PostCode="W01" Country="GB"/>
		</Guide>			
	</GuideList>
	<DestinationList>
		<Destination Id="1" DestinationName="Ayr" DestinationType="BnB" Access="">
			<Contact EmailId="contacts@ayr.com" MobilePhone="10039993" Landline="33434"/>
			<Address AddressLine1="1 High Street" AddressLine2="Ayr" AddressLine3="" AddressLine4="" Region="" PostCode="AY01" Country="GB"/>
		</Destination>
		<Destination Id="2" DestinationName="Irvine" DestinationType="BnB" Access="">
			<Contact EmailId="contacts@@Irvine.com" MobilePhone="089995993" Landline="33434"/>
			<Address AddressLine1="2 High Street" AddressLine2="Irvine" AddressLine3="" AddressLine4="" Region="" PostCode="IR01" Country="GB"/>
		</Destination>
		<Destination Id="3" DestinationName="Ardrossan" DestinationType="BnB" Access="">
			<Contact EmailId="contacts@Ardrossan.com" MobilePhone="70899939993" Landline="33434"/>
			<Address AddressLine1="3 High Street" AddressLine2="Ardrossan" AddressLine3="" AddressLine4="" Region="" PostCode="AR01" Country="GB"/>
		</Destination>
		<Destination Id="4" DestinationName="Largs" DestinationType="BnB" Access="">
			<Contact EmailId="ft.1@Largs.com" MobilePhone="40049993" Landline="33434"/>
			<Address AddressLine1="4 High Street" AddressLine2="Largs" AddressLine3="" AddressLine4="" Region="" PostCode="LA01" Country="GB"/>
		</Destination>
		<Destination Id="11" DestinationName="Ludlow " DestinationType="Hotel" Access="">
			<Contact EmailId="frontdesk@Ludlow.com" MobilePhone="787976648" Landline="33434"/>
